apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: tcp-test-gateway
  namespace: tcp-probe-test
  annotations:
    alb.networking.azure.io/alb-namespace: alb-test-infra
    alb.networking.azure.io/alb-name: alb-test
    cert-manager.io/cluster-issuer: letsencrypt-gateway
spec:
  gatewayClassName: azure-alb-external
  listeners:
  - name: http-listener
    port: 80
    protocol: HTTP
    hostname: alb.ms.waltken.de
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: tcp-test-route
  namespace: tcp-probe-test
spec:
  parentRefs:
  - name: tcp-test-gateway
  hostnames:
    - alb.ms.waltken.de
  rules:
  - backendRefs:
    - name: build-and-deploy
      port: 80
---
apiVersion: alb.networking.azure.io/v1
kind: HealthCheckPolicy
metadata:
  name: tcp-test-health-check-policy
  namespace: tcp-probe-test
spec:
  targetRef:
    group: ""
    kind: Service
    name: build-and-deploy
    namespace: tcp-probe-test
  default:
    protocol: TCP
    # If you change the tcp-probe to port 8080, the health check will pass
    # You can see the TCP health check executes a GET request to the / endpoint
    port: 6000
    interval: 10s
    timeout: 1s
    unhealthyThreshold: 3
    healthyThreshold: 1