apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: tcp-test-gateway
  namespace: namespace-workflow-1702560545407
  annotations:
    alb.networking.azure.io/alb-namespace: alb-test-infra
    alb.networking.azure.io/alb-name: alb-test
    cert-manager.io/cluster-issuer: letsencrypt-gateway
spec:
  gatewayClassName: azure-alb-external
  listeners:
  - name: http-listener
    port: 80
    protocol: HTTP
    hostname: alb.ms.waltken.de
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: tcp-test-route
  namespace: namespace-workflow-1702560545407
spec:
  parentRefs:
  - name: tcp-test-gateway
  hostnames:
    - alb.ms.waltken.de
  rules:
  - backendRefs:
    - name: build-and-deploy
      port: 80
---
apiVersion: alb.networking.azure.io/v1
kind: HealthCheckPolicy
metadata:
  name: tcp-test-health-check-policy
  namespace: namespace-workflow-1702560545407
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: tcp-test-route
    namespace: namespace-workflow-1702560545407
  default:
    protocol: TCP
    port: 6000
    interval: 10s
    timeout: 1s
    unhealthyThreshold: 3
    healthyThreshold: 1