apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-and-deploy
  labels:
    app: build-and-deploy
  namespace: tcp-probe-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: build-and-deploy
  template:
    metadata:
      labels:
        app: build-and-deploy
    spec:
      containers:
        - name: build-and-deploy
          image: ghcr.io/waeltken/tcp-probe/tcp-probe:latest
          ports:
            - containerPort: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 1
