apiVersion: v1
kind: Service
metadata:
  name: build-and-deploy
  namespace: tcp-probe-test
spec:
  selector:
    app: build-and-deploy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080