apiVersion: v1
kind: Service
metadata:
  name: build-and-deploy
  namespace: namespace-workflow-1702560545407
spec:
  type: LoadBalancer
  selector:
    app: build-and-deploy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: tcp
      protocol: TCP
      port: 3000
      targetPort: 3000