name: build-and-deploy
on:
    push:
        branches:
            - main
    workflow_dispatch: {}
env:
    ACR_RESOURCE_GROUP: aks-dev
    CLUSTER_NAME: cluster-dev
    CLUSTER_RESOURCE_GROUP: aks-dev
    CONTAINER_NAME: tcp-probe
    DEPLOYMENT_MANIFEST_PATH: |
        manifests/deployment.yaml
        manifests/service.yaml
        manifests/alb.yaml
jobs:
    buildImage:
        permissions:
            contents: read
            id-token: write
            packages: write
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Packages
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and publish to GitHub Packages
              uses: docker/build-push-action@v5
              with:
                builder: ${{ steps.buildx.outputs.name }}
                context: .
                file: ./Dockerfile
                push: true
                tags: ghcr.io/${{ github.repository_owner }}/tcp-probe/${{ env.CONTAINER_NAME }}:${{ github.sha }},ghcr.io/${{ github.repository_owner }}/tcp-probe/${{ env.CONTAINER_NAME }}:latest
    deploy:
        permissions:
            actions: read
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        needs:
            - buildImage
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v1
              name: Azure login
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            - uses: azure/aks-set-context@v3
              name: Get K8s context
              with:
                admin: "false"
                cluster-name: ${{ env.CLUSTER_NAME }}
                resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
                use-kubelogin: "true"
            - uses: Azure/k8s-deploy@v4
              name: Deploys application
              with:
                action: deploy
                images: ghcr.io/${{ github.repository_owner }}/tcp-probe/${{ env.CONTAINER_NAME }}:${{ github.sha }}
                manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
                namespace: tcp-probe-test
